hello_world:
    pattern: /hello/{name}.{_format}
    defaults:
        _controller: "AcmeHelloBundle:Default:hello"
        _format: "html"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api-doc

acme_api:
    resource: "@AcmeApiBundle/Controller"
    type: annotation
    prefix: /api
